---

#- name: Install prerequisite packages for Jekyll
#  apt: pkg={{ item }} state=present update_cache=yes
#  with_items:
#    -

### Install the Jekyll source

- include: ../../rvm/tasks/bundler.yml
  vars:
    rvm_user: "{{ jekyll.user }}"
    ruby_version: "{{ ruby.global }}"
    bundler_path: "{{ jekyll.path }}"

#- name: Install Jekyll Nginx.conf
  #template: src='nginx.conf.j2' dest='/etc/nginx/conf.d/nginx.conf'
  #notify: restart nginx

- name: Kill Jekyll
  command: pkill -9 -f jekyll
  ignore_errors: true

- name: Start Jekyll
  sudo_user: "root"
  command: /home/{{ jekyll.user }}/.rvm/bin/rvm {{ ruby.global }} exec bundle exec jekyll serve --watch --port 80 --detach chdir={{ jekyll.path  }}
  async: 45
  poll: 0
  register: jekyll_startup

- debug: msg="{{ jekyll_startup }}"
